DoAnChuyenNganh/Controllers/ABCController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnChuyenNganh.Models;
using PagedList;
using PagedList.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    public class ABCController : Controller
    {
        dbYTDataContext data = new dbYTDataContext();
        
        public ActionResult Index()
        {
         
            return View();
        }
        public List<Product> GetProducts(int count)
        {
            return data.Products.OrderByDescending(a => a.namepro).Take(count).ToList();
        }
        public ActionResult Product()
        {
            var product = from pro in data.Products select pro;
            return PartialView(product);
        }
        public ActionResult Details(int ?id)
        {
            var pro = from s in data.Products
                       where s.idpro == id
                       select s;
            return View(pro.SingleOrDefault());
        }

        public ActionResult All()
        {
            var cate = (from p in data.Categories join a in data.Products on p.idcate equals a.idcate where p.CStatus == true select p).Distinct();
            return PartialView(cate);
        }
        public ActionResult ProductAll(int id)
        {
            var proall = from s in data.Products where s.idcate == id select s;
            return View(proall);
        }
        public ActionResult NewestProduct()
        {
            var newpro = data.Products.OrderByDescending(p => p.idpro).Take(2);
            return PartialView(newpro);
        }
        public ActionResult Corporate()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Search(string search)
        {
            var pro = GetProducts(0);

            if (search == "" || search == null)
            {
                ViewData["tb1"] = "There are no products searched ";
                return View(pro);
            }
            else
            {
                ViewBag.keyword = search;
            }
            return View(data.Products.Where(s => s.namepro.Contains(search)).ToList());

            
        }
    }
}

DoAnChuyenNganh/Views/Shared/_LayoutABC1.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <title>LTH Medical Care</title>
    <meta charshet="utf-8" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link href="~/Content/teststyle2.css" rel="stylesheet" />

</head>
<body>
    <div style="color:white">
        @RenderSection("something", required: false)
        @RenderBody()
    </div>
    <div class="header">
        <div class="container" id="myHeader">
            <nav>
                <ul>
                    <li><a href="@Url.Action("Index","ABC")">Home <i class="fa fa-heartbeat" aria-hidden="true"></i></a></li>
                    <li><a href="@Url.Action("ProductAll","ABC",new { id = "1" })">Products <i class="fa fa-id-badge" aria-hidden="true"></i></a></li>
                    <li><a href="@Url.Action("Corporate","ABC")">Corporate <i class="fa fa-handshake-o" aria-hidden="true"></i></a></li>
                    <li><a href="@Url.Action("Contact","ABC")">Contact <i class="fa fa-address-card-o" aria-hidden="true"></i></a></li>
                    <li>
                        @using (Html.BeginForm("Search", "ABC"))
                        {
                            <div class="input-group input-group-lg" style="padding: 25px 50px;display: flex;">
                                <input name="search" type="text" class="form-control-lg" aria-label="Small" aria-describedby="inputGroup-sizing-sm" placeholder="Medical you li..." style="box-sizing: border-box; margin: 0; font-family: inherit; overflow: visible; display: block; color: #495057; background-color: #fff; background-clip: padding-box; border: 1px solid #ced4da; transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out; padding: .25rem .5rem; font-size: .875rem; line-height: 1.5; border-radius: .2rem; position: relative; flex: 1 1 auto; width: 100%; margin-bottom: 0; border-top-right-radius: 0; border-bottom-right-radius: 0;">

                                <button type="submit" class="btn btn-secondary btn-number" style="box-sizing: border-box; margin: 0; font-family: inherit; overflow: visible; text-transform: none; display: inline-block; font-weight: 400; text-align: center; white-space: nowrap; vertical-align: middle; user-select: none; border: 1px solid transparent; transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out; color: #fff; background-color: #6c757d; border-color: #6c757d; position: relative; z-index: 2; padding: .25rem .5rem; font-size: .875rem; line-height: 1.5; border-radius: .2rem; cursor: pointer; border-top-left-radius: 0; border-bottom-left-radius: 0;">
                                    <i class="fa fa-search"></i>
                                </button>

                            </div>
                        }
                    </li>
                    @{
                        if (Session["username"] == null)
                        {
                            <li><a href="@Url.Action("login","Man")">Login <i class="fa fa-sign-in"></i></a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("logout","Man")">Logout <i class="fa fa-sign-out"></i></a></li>
                        }
                    }
                    @Html.Action("CartPartial", "Cart")
                </ul>
            </nav>
        </div>
    </div>

</body>
</html>

DoAnChuyenNganh/Views/Shared/_LayoutFooter.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <title>LTH Medical Care</title>
    <meta charshet="utf-8" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link href="~/Content/teststyle2.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<footer>
    <div style="color:white">
        @RenderSection("something", required: false)
        @RenderBody()
    </div>
    <div class="container1">
        <div class="row">
            <div class="footer-col-1">
                <img src="~/Images2/truck.png" style="width:80px;height: 80px;">
                <p>456 Điện Biên Phủ, Quận BT, TP.HCM</p>
            </div>
            <div class="footer-col-2">
                <img src="~/Images2/mail.png" style="width:60px;height: 60px;">
                <p>testmail@gmail.com</p>
            </div>
            <div class="footer-col-3">
                <img src="~/Images2/phone.png" style="width:50px;height: 50px;">
                <p>Số tư vấn : 0973100740</p>
            </div>
            <div class="footer-col-4">
                <img src="~/Images2/facebook.png" style="width:70px;height: 70px;">
                <p>Trang liên kết chính thức của web</p>
            </div>
        </div>
        <hr>
        <p class="copyright">© 2021 LTH Hospital. All rights reserved. - CÔNG TY TNHH WEB NHÀ THUỐC </p>
        <p class="copyright">Giấy phép kinh doanh số 0107583890 do Sở KHĐT Tp. Hồ Chí minh cấp ngày 04/10/2021</p>
    </div>
</footer>

DoAnChuyenNganh/Views/Shared/_LayoutHeader.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <title>LTH Medical Care</title>
    <meta charshet="utf-8" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link href="~/Content/teststyle2.css" rel="stylesheet" />

</head>

<body>
    <div style="color:white">
        @RenderSection("something", required: false)
        @RenderBody()
    </div>
    <div class="header">
        <div class="container" id="myHeader">
            <nav>
                <ul>
                    <li><a href="@Url.Action("Index","ABC")">Home <i class="fa fa-heartbeat" aria-hidden="true"></i></a></li>
                    <li><a href="@Url.Action("All","ABC")">Products <i class="fa fa-id-badge" aria-hidden="true"></i></a></li>
                    <li><a href="@Url.Action("Corporate","ABC")">Corporate <i class="fa fa-handshake-o" aria-hidden="true"></i></a></li>
                    <li><a href="@Url.Action("Contact","ABC")">Contact <i class="fa fa-address-card-o" aria-hidden="true"></i></a></li>
                    <li>
                        @using (Html.BeginForm("Search", "ABC"))
                        {
                            <div class="input-group input-group-lg" style="padding: 25px 50px;display: flex;">
                                <input name="search" type="text" class="form-control-lg" aria-label="Small" aria-describedby="inputGroup-sizing-sm" placeholder="Medical you li..." style="box-sizing: border-box; margin: 0; font-family: inherit; overflow: visible; display: block; color: #495057; background-color: #fff; background-clip: padding-box; border: 1px solid #ced4da; transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out; padding: .25rem .5rem; font-size: .875rem; line-height: 1.5; border-radius: .2rem; position: relative; flex: 1 1 auto; width: 100%; margin-bottom: 0; border-top-right-radius: 0; border-bottom-right-radius: 0;">

                                <button type="submit" class="btn btn-secondary btn-number" style="box-sizing: border-box; margin: 0; font-family: inherit; overflow: visible; text-transform: none; display: inline-block; font-weight: 400; text-align: center; white-space: nowrap; vertical-align: middle; user-select: none; border: 1px solid transparent; transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out; color: #fff; background-color: #6c757d; border-color: #6c757d; position: relative; z-index: 2; padding: .25rem .5rem; font-size: .875rem; line-height: 1.5; border-radius: .2rem; cursor: pointer; border-top-left-radius: 0; border-bottom-left-radius: 0;">
                                    <i class="fa fa-search"></i>
                                </button>

                            </div>
                        }
                    </li>
                    @{
                        if (Session["username"] == null)
                        {
                            <li><a href="@Url.Action("login","ABC")">Login <i class="fa fa-sign-in"></i></a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("logout","ABC")">Logout <i class="fa fa-sign-out"></i></a></li>
                        }
                    }
                    <li>@Html.Action("CartPartial", "Cart")</li>
                </ul>
            </nav>
        </div>
    </div>

</body>
</html>

DoAnChuyenNganh/Views/Shared/_LayoutTesting.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        @Html.Partial("_LayoutHeader")
    </header>
    <div>
        @RenderBody()
    </div>
    @Html.Partial("_LayoutFooter")
</body>
</html>

DoAnChuyenNganh/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
<script>tinymce.init({ forced_root_block: false , selector: 'textarea' });</script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin Management", "Account", "Admin")</li>
                    <li>@Html.ActionLink("Category Management", "Category", "Admin")</li>
                    <li>@Html.ActionLink("Product Management", "Product", "Admin")</li>
                    <li>@Html.ActionLink("Bill Management", "Bill", "Admin")</li>
                    <li>@Html.ActionLink("Account Management", "Man", "Admin")</li>
                    @{
                        if (Session["TaikhoanAdmin"] != null)                  
                        {
                            <li><a href="@Url.Action("logout","Admin")">Logout <i class="fa fa-sign-out"></i></a></li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ABC Bakery</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>